### ISSUE TITLE
User can search for a specific volume

### ISSUE THREAD

**Issue by Andrew-Roide** [Andrew-Roide/Book-Library#1]
## ⚙️ Feature

Readers will want to search for their new or their favorite books.

## 📐 Functionality

Create a responsive webpage that allows users to search for a specific volume using Google Books API. 

## 🖼️ Wireframes

![Capture](https://github.com/Andrew-Roide/Book-Library/assets/63313798/f4f6cb5f-8b19-4802-8122-26c4cd4472d4)
![Capture2](https://github.com/Andrew-Roide/Book-Library/assets/63313798/886010a8-8cf5-4af4-a081-e6489d0b2e44)

## ✅ Task List

- [x] Create the starting HTML skeleton with the website name in the `nav-bar` header to match the figma.
- [x] Add two navbar links to match the figma. 
  - [x] One for the search webpage.
  - [x] One for the user's bookshelf webpage.
- [x] Below the `nav-bar` create a container to add a heading, description, search bar, and search button to match the figma.
- [x] Complete the HTML page using the appropriate responsive layout classes.
  - [x] Write CSS for mobile devices first.
  - [x] Adjust styling to fluidly adapt to desktop.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure the search input is `required`.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] In the `main.js` file add a function to `fetch` the Google Books API.
  - [x] throw new error if there's no response
  - [x] `console.log` the data to make sure information is being received.
- [x]  Add an event listener to the `search` button and attach the `fetch` function to it
- [x] Extract the results 
  - [x] display first 5 results of books
  - [x] loop through the data for the 5 results
  - [x] create a new object of the results to access the title, author, number of pages, isbn, and book cover
  - [x] provide edge cases if either title, author, number of pages, isbn, and book cover are not available
  
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
