### ISSUE TITLE
User can look through a list of search results / volumes returned

### ISSUE THREAD

**Issue by Andrew-Roide** [Andrew-Roide/Book-Library#2]
## ⚙️ Feature

view the search results matching the value the user typed in the search bar

## 📐 Functionality

users will be presented a list of books showing the title, author, ISBN, and number of pages

## 🖼️ Wireframes

![Capture3](https://github.com/Andrew-Roide/Book-Library/assets/63313798/81f4f726-07aa-49c8-8379-0c94cf1e3263)
![Capture4](https://github.com/Andrew-Roide/Book-Library/assets/63313798/febce17c-e666-4699-8273-9ab81f868ae7)
![Capture5](https://github.com/Andrew-Roide/Book-Library/assets/63313798/62947761-48dd-45a9-a7a7-11cceaf657aa)
![Capture6](https://github.com/Andrew-Roide/Book-Library/assets/63313798/25980986-caaa-4457-a2fc-62a635439ced)

## ✅ Task List
- [x] render a DOM tree page for the first 8 results matching the search request by the user
  - [x] have a title showing it's on the search results 
  - [x] each result should have a picture of the book cover, title, author, isbn, and number of pages
  - [x] each result should have an add button to allow the user to add the book to their bookshelf
- [x] render a DOM tree page if the search results return nothing from the API
- [x]  handle an error if the search results are empty
- [x] view swap from the search main page to the search results.
- [x] add eventListener to Find a Book
  - [x] reset resultsToDisplay  to empty
  - [x]  view swap back to the main page
  - [x] remove DOM tree

- **Clean Up**

- [x]  Remove all console logs.
- [x]  Remove all commented out code.
- [x]  Remove all CSS properties that have no effect.
- [x]  Check all code for proper formatting and indentation.
- [x]  Confirm that there are no errors in the console while using the application.
- [x]  Confirm that all previous functionality still works without errors.
- [x]  Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
