### ISSUE TITLE
User can add a volume to their their personal bookshelf

### ISSUE THREAD

**Issue by Andrew-Roide** [Andrew-Roide/Book-Library#3]
## ⚙️ Feature
be able to click on the add book button from the returned search result books

## 📐 Functionality

User will be able to add the book to their book library and receive conformation it was added successfully

## 🖼️ Wireframes

![Capture3](https://github.com/Andrew-Roide/Book-Library/assets/63313798/aa24a002-8d84-4382-9458-338201a7fc0e)
![Capture4](https://github.com/Andrew-Roide/Book-Library/assets/63313798/21880f34-e2ce-4228-bcd7-8e2c6f16fdf2)

## ✅ Task List

- [ ] add an event listener to the add book buttons to add the book to the new `object` as well as store it in `localstorage`
- [ ] differentiate the add book button for when the book was added or not
- [ ] display a message that the book was added successfully
- [ ] render a DOM tree page of their bookshelf with the books saved in `localstorage`
- [ ] sort the books alphabetically
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
