### ISSUE TITLE
User can delete a volume from their bookshelf

### ISSUE THREAD

**Issue by Andrew-Roide** [Andrew-Roide/Book-Library#4]
## ⚙️ Feature
user can view their bookshelf and delete any saved books they have saved

## 📐 Functionality
to delete any books from their bookshelf and view their books as well

## 🖼️ Wireframes
![Capture7](https://github.com/Andrew-Roide/Book-Library/assets/63313798/3a32f5bf-85d4-456d-aabb-c2d09bd50444)
![Capture8](https://github.com/Andrew-Roide/Book-Library/assets/63313798/ac757aad-ee04-4439-b11a-f3f6a5793dda)
![Capture9](https://github.com/Andrew-Roide/Book-Library/assets/63313798/a14180ae-4fcb-43f1-8949-5b7821510592)
![Capture10](https://github.com/Andrew-Roide/Book-Library/assets/63313798/c173f5dc-622f-431e-aed5-9c91fae86ebe)

## ✅ Task List

- [ ] render a DOM tree page to show the user's bookshelf from the saved books from local storage 
- [ ] have a delete button with an event listener to remove the selected book from local storage
- [ ] render a modal to confirm if user would like to delete the book
- [ ] update local storage if user deletes

- Clean Up

- [ ]  Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ]  Remove all console logs.
- [ ]  Remove all commented out code.
- [ ]  Remove all CSS properties that have no effect.
- [ ]  Check all code for proper formatting and indentation.
- [ ]  Confirm that there are no errors in the console while using the application.
- [ ]  Confirm that all previous functionality still works without errors.
- [ ]  Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ]  Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
